### ISSUE TITLE
Serial? what dependency is this?

### ISSUE THREAD

**Issue by Zartris** [joshnewans/diffdrive_arduino#7]
I cannot get serial to compile and I was hoping someone could inform me more on how to install this and make it visible for the cmake.

I thought it was the libserial-dev from the video, however that might not be the case anymore.

**Comment by lucasalberto01** [comment]
`sudo apt install libserial-dev` solved my problem

**Comment by Zartris** [comment]
Yea i realised that i was on main. 
And the video linked is pretty much the same as the humble branch
